### ISSUE TITLE
Hard Bans - 2 confirmed

### ISSUE THREAD

**Issue by RiC0MD** [disdain13/PokeRoadie#38] opened 2016-08-12 02:23 UTC
And then crash Obj ref not set to an instance of an obj.  PokeRoadieInventory.cs line 397 in the stack trace.

Abort, and possibly time out 5-10 mins and retry?

(Either servers are down or they just stepped up banning, hoping the former)

**Comment by RiC0MD** [comment] 2016-08-12 02:34
Appears this might have been an account ban, loading it on my phone results in "Failed to get game data from the server."

Will report back in the morning.

**Comment by disdain13** [comment] 2016-08-12 02:50
were you running multiple bots? think about what you were doing, what possibly could have triggered the ban.Let me know if you find out more. Thanks

**Comment by RiC0MD** [comment] 2016-08-12 03:08
Nope, literally only thing running on that IP, tried my account locally and get the same message.  So its not IP related, but it was running non-stop for 2 days now.  Ill check it again in the morning, could be a temp issue, but we'll see.

**Comment by RiC0MD** [comment] 2016-08-12 13:44
Does seem like that account has been banned, very interesting. @disdain13 I'm thinking using this account to trace down the crash, but also possible perm ban detection? If you think its worth it?

**Comment by RiC0MD** [comment] 2016-08-12 13:47
What's interesting, I see other report http://i.imgur.com/DSaChPr.jpg when the account is banned, but I do not see this, I just see "Failed to get game data from the server." from the official app.

**Comment by disdain13** [comment] 2016-08-12 14:20
My home account was banned, I sent Niantic an email complaining... They replied:

_Trainer,

We have received your appeal. Our goal is to provide a fair, fun and legitimate game experience for everyone. Use of any other third-party software or app, including but not limited to scripts/apps, applications used to falsify your location, using emulators, modified or unofficial software and/or accessing Pokémon GO clients or backends in an unauthorized manner is considered cheating.

-NianticOps_

**Comment by disdain13** [comment] 2016-08-12 14:21
Wanna see my reply to their reply?

**Comment by disdain13** [comment] 2016-08-12 14:21
Niantic:

Possibly. However, I have payed for pokecoins on this account. According to US commerce law, you cannot deny delivery or access to my agreed up digital currency conversion (us dollars to pokecoins) without a full refund for said currencies. I did not pay for access to PokemonGo, and if you wish to remove access that is fine. However, you cannot remove access to my converted digital currencies or pending transactions, revoking delivery/access of said currencies without refund is against us law. For example, my bank cannot close out my account without establishing a zero balance. And neither can you.

**Comment by disdain13** [comment] 2016-08-12 14:23
LOL, not that I care about 1000 pokecoins I payed for, just wanted to throw their legal team in a whirl!

**Comment by RiC0MD** [comment] 2016-08-12 14:25
Hahah very nice, but also makes me wonder how they detected it.  I know my brother is using Nerco and his account is fine, but he's also being very careful to take 'breaks', turn it off overnight, etc, so I wonder if that's the only difference.

**Comment by disdain13** [comment] 2016-08-12 14:28
I worked on a few changes last night. Let me check them in. Minimized the forced calls to GetMapObjects, made delays between actions configurable.

**Comment by disdain13** [comment] 2016-08-12 14:29
I also added the settings for AutoFavorite and AutoRename

**Comment by disdain13** [comment] 2016-08-12 14:34
Ok, checked in. Now MinDelay MaxDelay can control pauses between actions. Reduced hard calls to getMapObjects by 1200%

**Comment by disdain13** [comment] 2016-08-12 14:35
also reduced hard calls to inventory

**Comment by RiC0MD** [comment] 2016-08-12 14:50
Does your account actually show 'banned' from the official app?

**Comment by disdain13** [comment] 2016-08-12 14:55
Nope, same symptom as you. But, as one of the few bot developers, I am probably on a special list. Their reply did not contain a hint of concern for customer retainment, just "your a cheat!". From an intelligence perspective, this tells me they know who I am. So, our accounts may have a special ban, in attempt to prevent us from detecting it.

**Comment by disdain13** [comment] 2016-08-12 14:56
There is no doubt they are monitoring these github branches, and the conversations within them as well.

**Comment by disdain13** [comment] 2016-08-12 15:11
@RiC0MD - if you want to put in a hard ban message feel free to do it. PokeRoadieInventory line 397, instead of just returning the empty list, also Logger a message about the perma ban then return.

**Comment by lukezona** [comment] 2016-08-12 15:13
@RiC0MD The screenshot you have linked is clearly a fake.

There's no evidence of permaban at the moment, but it's possible that Niantic have started a ban wave.

There are new types of Hard Ban (for a lot of hours) but nothing permanent confirmed at the moment.

**Comment by Skolzack** [comment] 2016-08-12 15:15
I'm hardbanned more than 10hours and still. I can't spin pokestops, quickspin don't work, necrobot bypass don't work but i can catch pokemons, transfer, open eggs etc. Shame on you niantic

**Comment by RiC0MD** [comment] 2016-08-12 15:15
I'm going to keep monitoring it, @disdain13 stuck on a webex for most the day, so can't open VS :(

**Comment by heobaccuc** [comment] 2016-08-12 16:06
well i bot only one account anf turn off last night wake up this morning keep sayign server down...so i try log on manually with my phone it saying.....cant get data from server...so i guess i am hard banned too?

**Comment by htanh034** [comment] 2016-08-12 16:17
error ???

[23:16:37](INFO) Found 1 Pokemon for Evolve:
[23:16:37](EVOLVE ERROR) Poliwhirl 234 V |  529 Cp | 30,31% | Lvl 16 - FailedPokemonMissing
[23:16:39](INFO) Found 3 pokemon to transfer...
[23:16:39](ERROR) Transfer Error - Failed
[23:16:40](ERROR) Transfer Error - Failed
[23:16:41](ERROR) Transfer Error - Failed

**Comment by disdain13** [comment] 2016-08-12 16:21
I am looking into it

**Comment by disdain13** [comment] 2016-08-12 16:24
btw, I think the fact that Niantic now has an "appeal a ban" page, might signify that a long-term ban is/has/will happen.

**Comment by disdain13** [comment] 2016-08-12 16:25
Just checked my sons account. Very strange, I get the same error when trying to run the bot against his account. But, he seems to login just fine via device. My account, I cannot log in at all, even via device.

**Comment by disdain13** [comment] 2016-08-12 16:40
NecroBot is gone... Checkout their github.

**Comment by htanh034** [comment] 2016-08-12 16:41
me too. But try again login it ok

**Comment by pietsteph** [comment] 2016-08-12 17:03
got a transfer and evolve fail too.. what to do?

*btw I'm PokeRoadie user and moved to Necro but it's down :smile:

**Comment by disdain13** [comment] 2016-08-12 18:49
I am working on the transfer/errors. It has to do with the latest release. I would not go back a release because it might cause detection. Just wait it out, I will have a new release out tonight.

**Comment by disdain13** [comment] 2016-08-12 18:57
published new release for transfer / evolve errors. Let me know how it goes.

**Closed as completed** 2016-08-12 19:01 UTC
Labels: bug, enhancement
