### ISSUE TITLE
Issue with 'No location in your area'

### ISSUE THREAD

**Issue by EndofZ** [disdain13/PokeRoadie#33] opened 2016-08-11 11:22 UTC
Hi, I've scoured the wiki, the posted issues and google as well as I could but I haven't found a fix to this. Logging in with the account I'm using for this in the app shows me that I'm there, I'm able to catch pokemon and visit stops. But when I run the bot at those coordinates the only thing I get is 

[13:16:38](ATTENTION) No locations in your area...

This repeats over and over. I'll attach a screencap and my settings.xml
This is a super low priority issue, as the account I'm using is just a second, throwaway account in the game, to have some fun with bots and such. The only bot I run with this account is Pokeroadie and that's the only bot I run period, I know it's bad to run multiple bots off the same IP. But I don't think I'm banned, since I can just log in with this account in the app and play normally, as mentioned above. Any help would be appreciated and kudos on the bot, just because I can't get it to work, doesn't mean it's bad!
![pokeroadie screencap](https://cloud.githubusercontent.com/assets/20968981/17587103/5c8c92e4-5fc6-11e6-9520-960cc172c270.png)
[Settings.xml.txt](https://github.com/disdain13/PokeRoadie/files/413033/Settings.xml.txt)

**Comment by disdain13** [comment] 2016-08-11 13:55
This is because your IP address has be banned. This generally happens if you run two or more instances of any bot from a single IP. Good news though, these bans only seem to last about 4 hours. I got banned yesterday, and it is working fine now. Everything seems to work, but no pokestop or gym info is returned from getMapObjects call, it is the hard ban.

**Comment by disdain13** [comment] 2016-08-11 13:56
If two different accounts are accessed at the same time from the same ip, it will trigger the ban. Multi-botting will now require Proxy, which we are working on integrating.

**Comment by disdain13** [comment] 2016-08-11 14:00
duplicate of [ticket 30](https://github.com/disdain13/PokeRoadie/issues/30)

**Closed as completed by disdain13** 2016-08-11 14:00 UTC
Labels: duplicate

**Comment by EndofZ** [comment] 2016-08-11 14:15
Yep, totally works now.

**Comment by poke26** [comment] 2016-10-08 14:47
I have the same exact issue except the "attention no locations in your area still keep going since yesterday :(((
What should i do
